global using AutoMapper;
global using JSB.Data;
global using JSB.DTO;
global using JSB.Models;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using static System.Reflection.Metadata.BlobBuilder;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection.Emit;
global using System.Reflection.Metadata;
global using System.Reflection;
global using System.Text.Json;
